---

site_name: MyArchive
site_url: http://127.0.0.1:8000

database:
  default: mysql
  mysql:
    host: 127.0.0.1
    port: 3306
    db: asagi
    user: asagi
    password: asagi
    charset: utf8mb4
  postgresql:
    host: 127.0.0.1
    port: 5432
    db: asagi
    user: asagi
    password: asagi
    charset: utf8

reports_db:
  default: mysql
  mysql:
    host: 127.0.0.1
    port: 3306
    db: ayase
    user: ayase
    password: ayase
    charset: utf8mb4
    
schema:
  name: asagi

archives:
  - {shortname: a, name: Anime & Manga}
  - {shortname: aco, name: Adult Cartoons}
  - {shortname: an, name: Animals & Nature}
  - {shortname: c, name: Cute}
  - {shortname: co, name: Comics & Cartoons}
  - {shortname: d, name: Hentai/Alternative}
  - {shortname: fit, name: Fitness}
  - {shortname: his, name: History & Humanities}
  - {shortname: int, name: International}
  - {shortname: k, name: Weapons}
  - {shortname: m, name: Mecha}
  - {shortname: mlp, name: Pony}
  - {shortname: q, name: 4chan Feedback}
  - {shortname: qa, name: Question & Answer}
  - {shortname: r9k, name: ROBOT9001}
  - {shortname: tg, name: Traditional Games}
  - {shortname: trash, name: Off-Topic}
  - {shortname: vr, name: Retro Games}
  - {shortname: wsg, name: Worksafe GIF}

boards:
  - {shortname: p, name: Photography}

skins:
  - {slug: default, name: FoolFuuka - Default}
  - {slug: midnight, name: FoolFuuka - Midnight}
  - {slug: kurimasu, name: FoolFuuka - Christmas}
  - {slug: barentain, name: FoolFuuka - Valentine's Day}
  - {slug: halloween, name: FoolFuuka - Halloween}

default_skin: default

options:
  post_selector: true
  stats: false
  ghost: false
  reports: true
  
image_location:
  image: /img/{board_name}/image
  thumb: /img/{board_name}/thumb

scraper:
  default: asagi
  asagi:
    name: Asagi
    source: https://github.com/eksopl/asagi
  ena:
    name: Ena
    source: https://github.com/shiimizu/ena

debug: false

session_secret: top_secret

oauth2:
 provider: gitgud
 login_url: https://gitgud.io/oauth/authorize
 token_url: https://gitgud.io/oauth/token
 userinfo_url: https://gitgud.io/oauth/userinfo
 client_id: a8537e1a862a53d440977bcb790cc104d6ecd5215466141 #example
 secret: 77bcb790cc104d6ecd521546614140b43e5bfc5b83 #example
 cookie_expiration: 86400 #24 * 3600, 24 hours
 groups: 
    admins: gitgud-admins
    moderators: gitgud-moderators
    #janitors: gitgud-janitors
