---
mysql:
  host: 127.0.0.1
  port: 3306
  db: asagi
  user: asagi
  password: asagi

site_name: FoolFuuka

archives:
  - {shortname: g, name: Technology}
  - {shortname: a, name: Anime & Manga}
  - {shortname: c, name: Cute}
  - {shortname: jp, name: Otaku Culture}
  - {shortname: int, name: International}
  - {shortname: ck, name: Food & Cooking}
  - {shortname: pol, name: Politically Incorrect}
  - {shortname: p, name: Photography}

boards:
  - {shortname: p, name: Photography}

skins:
  - {slug: default, name: FoolFuuka - Default}
  - {slug: midnight, name: FoolFuuka - Midnight}
  - {slug: kurimasu, name: FoolFuuka - Christmas}
  - {slug: barentain, name: FoolFuuka - Valentine's Day}
  - {slug: halloween, name: FoolFuuka - Halloween}

default_skin: default

schema:
  name: asagi
  
image_location:
  image: /img/{board_name}/image
  thumb: /img/{board_name}/thumb
